/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App app;

    @BeforeEach
    void set(){
        app = new App();
    }
    @Test
    void runTest() throws Exception {
        App.main(null);
    }
    @Test
    void priceTestWeak1() throws Exception {
        assertEquals(100, app.getPrice(true,false,12,4,25));
        assertEquals(200, app.getPrice(false,false,12,4,25));
    }
    @Test
    void priceTestWeak2() throws Exception {
        assertEquals(140, app.getPrice(false,true,12,4,25));
        assertEquals(200, app.getPrice(false,false,12,4,25));
    }
    @Test
    void priceTestWeak3() throws Exception {
        assertEquals(160, app.getPrice(false,false,6,4,25));
        assertEquals(200, app.getPrice(false,false,12,4,25));
    }
    @Test
    void priceTestWeak4() throws Exception {
        assertEquals(250, app.getPrice(false,false,12,6,25));
        assertEquals(200, app.getPrice(false,false,12,4,25));
    }
    @Test
    void priceTestWeak5() throws Exception {
        assertEquals(160, app.getPrice(false,false,12,4,10));
        assertEquals(200, app.getPrice(false,false,12,4,25));
    }
    @Test
    void priceTestStrong1() {
        assertThrows(Exception.class, ()-> {
            app.getPrice(false, false, 4, 4, 25);
        });
        assertThrows(Exception.class, ()-> {
            app.getPrice(false, false, 23, 4, 25);
        });

    }
    @Test
    void priceTestStrong2() {
        assertThrows(Exception.class, ()-> {
            app.getPrice(false, false, 12, 4, 2);
        });
        assertThrows(Exception.class, ()-> {
            app.getPrice(false, false, 12, 4, 76);
        });

    }
    @Test
    void priceTestStrong3() throws Exception {
        assertEquals(125, app.getPrice(true,false,12,6,25));
        assertEquals(250, app.getPrice(false,true,12,6,25));
        assertEquals(250, app.getPrice(false,false,6,7,25));
        assertEquals(250, app.getPrice(false,false,12,7,10));
    }
    @Test
    void priceTestStrong4() throws Exception {
        assertEquals(160, app.getPrice(false,false,12,4,60));
    }
}
