/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradeDisplayer;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class AppTest {
    App app;
    @BeforeEach
    public void setUp(){
        app = spy(App.class);
    }

    @Test
    public void averageComputerTest() {
        //stub
        when(app.gradeDB(10))
                .thenReturn(new int[][]{{10,10,10},{20,20,20}});
        int[][] subject = app.gradeDB(10);
        int[] exp_grade = app.averageComputer(subject);
        int[] real_grade = {10,20};
        assertArrayEquals(exp_grade, real_grade);
    }
    @Test
    void gradeSorterTest(){
        int[][] useless = new int[][]{{1,2,3}};
        when(app.averageComputer(useless))
                .thenReturn(new int[]{30,20,10});
        int[] grade = app.averageComputer(useless);
        int[] exp_grade = app.gradeSorter(grade);
        int[] real_grade = {10,20,30};
        assertArrayEquals(exp_grade,real_grade);
    }
    @Test
    void gradeCollecterTest(){
        when(app.gradeDB(3))
                .thenReturn(new int[][]{{10,20,30},{60,70,80},{100,90,80}});
        int[] exp_grade = app.gradeCollecter(3);
        System.out.println(Arrays.toString(exp_grade));
        int[] real_grade = {20,70,90};
        assertArrayEquals(exp_grade,real_grade);
    }

}
